name: "Bioinformatics and Statistical Genetics!"
description: "Felix Yanhui Fan's personal website"

url: "http://localhost:4000"

paginate: 10

# markdown: rdiscount
markdown: redcarpet
permalink: pretty
pygments: true
