name: "Statistics and Programming!"
description: "Felix Yanhui Fan's personal website"

author :
  name : Felix Yanhui Fan
  email : nolanfyh@gmail.com
  github : felixfan
  
url: "http://localhost:4000"

gems: ["jekyll-paginate"]
paginate: 5
paginate_path: "page:num"

# markdown: rdiscount 
# redcarpet2 isn't available on the Github version of the jekyll engine
# markdown: kramdown
# markdown: maruku

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data","superscript","highlight"]

permalink: pretty
highlighter: pygments

analytics :
  provider : google
  google :
    tracking_id : 'UA-44240871-1'

tags:
- jekyll
- code
