markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
permalink: /:title/
url: http://felixfan.github.io
name: "Statistics and Programming"
author: Felix Yanhui Fan
email: felixfanyh@gmail.com
github: felixfan
duoshuo: felixfan
researchgate: Yan-Hui_Fan
linkedin: fanfelix
googlescholar: 8fX1TSQAAAAJ
highlighter: rouge
gems: ["jekyll-paginate"]
paginate: 20
paginate_path: "page:num"
analytics :
  provider : google
  google :
    tracking_id : 'UA-44240871-1'
tags:
- jekyll
- code
about: "Felix Yanhui Fan's personal website"
